-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: 0f7b5e0c4f9f0a7516ae84be9df898e02fd34833
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
