-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: 31853d6c43b033713bc71d991f52b2b390a9bffc
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
