repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: 3842bea65a5382a4ef86102ecff04cf4964db37d
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
