-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: d71699d7cdd02d54568209711934ad35c8e89dd7
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
