repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
