-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: f0bf512dbb1a9a23ce022551b31fbfc54be8cd0d
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
