-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: d61d4a26db08e631daacba20d6fd346d918aac95
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
