repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: 11a996eec600aa64d1cc12859d9bffbc6422836c
    hooks:
    -   id: trailing-whitespace
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
